### ISSUE TITLE
'ViroARScene' cannot be used as a JSX component.s:open 

### ISSUE THREAD

**Issue by maysa-oueslati** [NativeVision/viro-test-bed#2]
I'm integrating viro react to an expo project for the first time and I'm facing the following  error with every viro component I'm trying to add :'ViroARScene' cannot be used as a JSX component.s:open

**Comment by robertjcolley** [comment]
Closing since this is no longer considered a starter-kit project. Please start from one of the starter kits that have been updated recently! :)
