### ISSUE TITLE
Native module VRTMaterialManager tried to override MaterialManager. Check the getPackages() method in MainApplication.java

### ISSUE THREAD

**Issue by monkeyK1n9** [NativeVision/viro-test-bed#3]
## Introduction

When I clone the app into my machine, I have this error. I didn't change the code.

How can I solve it?

## Screenshot

![image](https://user-images.githubusercontent.com/91855362/206882306-71698f90-aa8e-4388-88f5-a53a3e359618.png)

## How to reproduce

Clone the app and run it on device. I am using a samsung A52 with android 13.

**Comment by enricorobazza** [comment]
Have you found a solution to this?

**Comment by TheGB0077** [comment]
I got rid of this by removing

packages.add(new ReactViroPackage(ReactViroPackage.ViroPlatform.valueOf("OVR_MOBILE")));
and 
packages.add(new ReactViroPackage(ReactViroPackage.ViroPlatform.valueOf("GVR")));

at the MainApplication.java file. I only needed support for AR by all means.
